#!/bin/bash
if [[ -z "$1" ]]; then
    az account list -o table --only-show-errors
else
   if [[ "$1" == "-h" ]]; then
       echo ""
       echo "----------------------------------------------------------------------------------------------------------"
       echo " Azure Account Management"
       echo ""
       echo " View current subscriptions and change the Azure CLI active subscription."
       echo ""
       echo " usage:"
       echo ""
       echo " azac                                             - list all subscriptions available under current login"
       echo " azjit mgmt | conn                                - shortcuts to most frequently used subs"
       echo " azjit <subid>                                    - set subscription by subscription ID"
       echo "-----------------------------------------------------------------------------------------------------------"
       echo ""
   else
       if [[ "$1" == "mgmt" ]]; then
           echo "Account set to Management"
	   if [ -z $(az account list --query '[].name' -o tsv | grep "Saros-Management") ]; then
              az account set --name "MS-Management"
	   else
	      az account set --name "Saros-Management"
	   fi
       else
           if [[ "$1" == "conn" ]]; then
               echo "Account set to Connectivity"
	       if [ -z $(az account list --query '[].name' -o tsv | grep "Saros-Connectivity") ]; then
                  az account set --name "MS-Connectivity"
               else
                  az account set --name "Saros-Connectivity"
               fi
           else
	       echo "Account set to "$(az account show --subscription $1 --query 'name' -o tsv) 
               az account set --subscription $1
           fi
       fi
    fi
fi
