#!/bin/bash
if [ -z "$1" ]; then
    az network express-route list-service-providers -o table
else
    if [ -z "$2" ]; then
	az network express-route list -g $1 -o table --query "[].{RG:resourceGroup, Name:name, Loc:location, State:serviceProviderProvisioningState, Key:serviceKey}"
    else
        if [ "$1" == "-p" ]; then
            az network express-route list-service-providers --query "[? contains(name, '$2')].[{Locations:peeringLocations}]"
        else
            if [ "$1" == "-l" ]; then
                az network express-route list-service-providers --query "[? contains(peeringLocations, '$2')].{Name:name}" -o table
            else
                if [ "$1" == "-b" ]; then
                    az network express-route list-service-providers --query "[? contains(name, '$2')].[{Bandwidths:bandwidthsOffered}]"
                else
	            az network express-route list-route-tables -g $1 -n $2 --path primary --peering-name AzurePrivatePeering --only-show-errors | jq -r '["network","nexthop","path"], (.value[] | [.network,.nextHop,.path]) | @csv' | csvlook -I
                fi
             fi
         fi
     fi
fi
