#!/bin/bash
if [ -z "$1" ]; then
    az network vwan list -o table --query "[*].{RG:resourceGroup, VWan:name, Loc:location, State:provisioningState}"
else
    if [ -z "$2" ]; then
        az network vhub list -g $1 -o table --query "[*].{Name:name, Loc:location, Network:addressPrefix, State:routingState}"
    else
	if [ "$2" == "rt" ]; then
            for vhubname in `az network vhub list -g $1 --query "[].id" -o tsv | rev | cut -d'/' -f1 | rev`
            do
                for routetable in `az network vhub route-table list --vhub-name $vhubname -g $1 --query "[].id" -o tsv`
                do
                    if [ "$(echo $routetable | rev | cut -d'/' -f1 | rev)" != "noneRouteTable" ]; then
                        echo -e vHUB: $vhubname 
                        echo -e Effective route table: $(echo $routetable | rev | cut -d'/' -f1 | rev)   
                        az network vhub get-effective-routes -g $1 -n $vhubname \
                            --resource-type RouteTable \
                            --resource-id $routetable \
                            --query "value[].{addressPrefixes:addressPrefixes[0], asPath:asPath, nextHopType:nextHopType}" \
                            --output table
                        echo
                    fi
                done
            done
	fi
    fi
fi
