#!/bin/bash
if [ -z "$1" ]; then
    echo "usage:"
    echo "azjit rg              - list policies"
    echo "azjit rg -a vm        - add policy to a vm"
    echo "azjit rg vm           - initiate access to vm"
else
    subid=$(az account show --query 'id' -o tsv)
    if [ -z "$2" ]; then
        uri='https://management.azure.com/subscriptions/'$subid'/resourceGroups/'$1'/providers/Microsoft.Security/jitNetworkAccessPolicies?api-version=2020-01-01'
        az rest --method GET --url $uri
    else
        if [ "$2" == "-a" ]; then
            loc=$(az group show -g $1 --query 'location' -o tsv)
            uri='https://management.azure.com/subscriptions/'$subid'/resourceGroups/'$1'/providers/Microsoft.Security/locations/'$loc'/jitNetworkAccessPolicies/'$3'?api-version=2020-01-01'
            json='{
            "kind": "Basic",
            "properties": {
                "virtualMachines": [
                {
                    "id": "/subscriptions/'$subid'/resourceGroups/'$1'/providers/Microsoft.Compute/virtualMachines/'$3'",
                    "ports": [
                    {
                        "number": 22,
                        "protocol": "*",
                        "allowedSourceAddressPrefix": "*",
                        "maxRequestAccessDuration": "PT24H"
                    },
                    {
                        "number": 3389,
                        "protocol": "*",
                        "allowedSourceAddressPrefix": "*",
                        "maxRequestAccessDuration": "PT24H"
                    }
                    ]
                }
                ]
            }
            }'

            az rest --method PUT \
                --url $uri  \
                --body "$json"
        else
            loc=$(az group show -g $1 --query 'location' -o tsv)
            ip=$(curl -s -4 ifconfig.io)
	    uri='https://management.azure.com/subscriptions/'$subid'/resourceGroups/'$1'/providers/Microsoft.Security/locations/'$loc'/jitNetworkAccessPolicies/'$2'?api-version=2020-01-01'
            ports=$(az rest --method GET --url $uri | jq ".properties.virtualMachines[].ports[].number")
            uri='https://management.azure.com/subscriptions/'$subid'/resourceGroups/'$1'/providers/Microsoft.Security/locations/'$loc'/jitNetworkAccessPolicies/'$2'/initiate?api-version=2020-01-01'

            json='{
            "virtualMachines": [
                {
                "id": "/subscriptions/'$subid'/resourceGroups/'$1'/providers/Microsoft.Compute/virtualMachines/'$2'",
                "ports": ['
		i=0
		len=${#ports[@]}
		echo $len
                for port in $ports
		do
                    json+='{
                    "number": "'$port'",
                    "duration": "PT12H",
                    "allowedSourceAddressPrefix": "'$ip'"
                    }'
	            ((i=i+1))
	            if [ $i -le $len ]; then
	                json+=','
		    fi
	        done
                json+=']
                }
            ],
            "justification": "GBB doing our thang ....."
            }'
            az rest --method POST \
                --url $uri  \
                --body "$json"  \
                --output none
        fi
    fi
fi
