#!/bin/bash
if [ -z "$1" ]; then
    echo "usage:"
    echo "azjit rg              - list policies"
    echo "azjit rg -a vm        - add policy to a vm"
    echo "azjit rg vm           - initiate access to vm"
else
    subid=$(az account show --query 'id' -o tsv)
    if [ -z "$2" ]; then
        uri='https://management.azure.com/subscriptions/'$subid'/resourceGroups/'$1'/providers/Microsoft.Security/jitNetworkAccessPolicies?api-version=2020-01-01'
        az rest --method GET --url $uri
    else
        if [ "$2" == "-a" ]; then
            loc=$(az group show -g $1 --query 'location' -o tsv)
            myvar=$4
            ports=(`echo $myvar | tr ',' ' '`)
            uri='https://management.azure.com/subscriptions/'$subid'/resourceGroups/'$1'/providers/Microsoft.Security/locations/'$loc'/jitNetworkAccessPolicies/'$3'?api-version=2020-01-01'
            json='{
            "kind": "Basic",
            "properties": {
                "virtualMachines": [
                {
                    "id": "/subscriptions/'$subid'/resourceGroups/'$1'/providers/Microsoft.Compute/virtualMachines/'$3'",
                    "ports": ['
		            len=${#ports[@]}
                    for (( i=0; i<$len; i++ ))
		            do
                        json+='{
                        "number": "'${ports[$i]}'",
                        "duration": "PT24H",
                        "allowedSourceAddressPrefix": "'$ip'"
                        }'
	                    if [ $i -lt $((len-1)) ]; then
	                        json+=','
		                fi
	                done
                    json+=']                
                    }
                ]
            }
            }'

            az rest --method PUT \
                --url $uri  \
                --body "$json"
        else
	    if [ -z $3 ]; then
                dur=12
	    else
	        dur=$3
	    fi
            loc=$(az group show -g $1 --query 'location' -o tsv)
            ip=$(curl -s -4 ifconfig.io)
	        uri='https://management.azure.com/subscriptions/'$subid'/resourceGroups/'$1'/providers/Microsoft.Security/locations/'$loc'/jitNetworkAccessPolicies/'$2'?api-version=2020-01-01'
            myvar=$(az rest --method GET --url $uri | jq ".properties.virtualMachines[].ports[].number")
            ports=(`echo $myvar`)
            uri='https://management.azure.com/subscriptions/'$subid'/resourceGroups/'$1'/providers/Microsoft.Security/locations/'$loc'/jitNetworkAccessPolicies/'$2'/initiate?api-version=2020-01-01'
            json='{
            "virtualMachines": [
                {
                "id": "/subscriptions/'$subid'/resourceGroups/'$1'/providers/Microsoft.Compute/virtualMachines/'$2'",
                "ports": ['
		        len=${#ports[@]}
                for (( i=0; i<$len; i++ ))
		        do
                    json+='{
                    "number": "'${ports[$i]}'",
                    "duration": "PT'$dur'H",
                    "allowedSourceAddressPrefix": "'$ip'"
                    }'
	                if [ $i -lt $((len-1)) ]; then
	                    json+=','
		            fi
	            done
                json+=']
                }
            ],
            "justification": "GBB doing our thang ....."
            }'
            
            az rest --method POST \
                --url $uri  \
                --body "$json"  \
                --output none
        fi
    fi
fi
