#!/bin/bash
if [ -z "$1" ]; then
    az group list --query "[? !(contains(name, 'DefaultResourceGroup')) && !(contains(name, 'NetworkWatcher'))] | [].{name:name, loc:location, state:properties.provisioningState} | sort_by([], &name)" -o table
else
    if [ "$1" == "-a" ]; then
        az group list --query "[].{name:name, loc:location, state:properties.provisioningState} | sort_by([], &name)" -o table
    else
        if [[ -z "$2" ]]; then
	    az resource list -g $1 --query "[].{ name: name, flavor: kind, Resourcetype: type, region: location, state: provisioningState } | sort_by([], &Resourcetype)" -o table
	else
	    if [ "$1" == "-d" ]; then
	        az group delete -n $2 --no-wait
            fi 
	fi
    fi
fi
