#!/bin/bash
if [ -z "$1" ]; then
    az vm list -o table --query "[*].{Rg:resourceGroup, Loc:location, VM:name, OS:storageProfile.imageReference.offer, Sku:storageProfile.imageReference.sku}"
else
    if [ -z "$2" ]; then
        az vm list -g $1 --show-details -o table --query "[*].{VM:name, Size:hardwareProfile.vmSize, OS:storageProfile.osDisk.osType, IP:privateIps, PIP:publicIps, Loc:location, State:powerState, admin:osProfile.adminUsername, FQDN:fqdns}"
    else
        if [ "$2" == "start" ]; then
	    vmlist=$(az vm list -g $1 --query '[].name' -o tsv)
	    for i in $vmlist
            do
                echo "starting "$i
                az vm start -g $1 -n $i --no-wait
            done
        else
	    if [ "$2" == "stop" ]; then
                vmlist=$(az vm list -g $1 --query '[].name' -o tsv)
                for i in $vmlist
                do
                    echo "stopping "$i
                    az vm deallocate -g $1 -n $i --no-wait
                done
	    else
	        if [ "$2" == "-d" ]; then
		    echo "delete VM coming soon"
		else
		    if [ "$2" == "-da" ]; then
		        echo "DELETE all VM objects coming soon"
		    fi
	        fi
	    fi
        fi
    fi
fi
