#!/bin/bash
if [ -z "$1" ]; then
    az vm list -o table
else
    az vm list -g $1 --show-details -o table --query "[*].{VM:name, Size:hardwareProfile.vmSize, OS:storageProfile.osDisk.osType, IP:privateIps, PIP:publicIps, Loc:location, State:powerState, admin:osProfile.adminUsername, FQDN:fqdns}"
fi
